---
- name: reload sysctl
  become: true
  ansible.builtin.command: sysctl --system
  changed_when: false

- name: reload firewalld
  become: true
  ansible.builtin.command: firewall-cmd --reload
  changed_when: false
