---
collections:
  - name: ansible.netcommon
    version: "8.4.0"
  - name: arista.eos
    version: "12.0.1"
  - name: cisco.ios
    version: "11.3.0"
  - name: community.general
    version: "12.5.0"
  - name: community.network
    version: "5.1.0"
  - name: awx.awx
    version: "24.6.1"
