"""Render + atomically write a dnsmasq hosts file for flax-classify devices.

dnsmasq's `hostsdir` auto-reloads when a file in it changes, so the writer is
change-gated: it only rewrites when the rendered content differs from what is
already on disk, avoiding needless reload churn. Output is deterministic
(address lines sorted) so identical record sets render byte-identical.
"""

import os

_HEADER = "# generated by flax-classify -- do not edit"


def render_hosts(records):
    """Render `records` as a dnsmasq hosts file.

    `records` is a list of {"hostname", "ipv4", "ipv6"[, "aliases"]} dicts. Emit
    one "<ip>\t<hostname>[ alias1 alias2 …]" line per non-falsy address (A and
    AAAA). Optional `aliases` (a list of operator-set DNS names from
    user_context.aliases) are appended as additional space-separated names on the
    line — dnsmasq's hostsdir format resolves every name on the line to that IP.
    Sorted for a stable, order-independent result, behind a fixed header comment,
    with a trailing newline.
    """
    lines = []
    for rec in records:
        names = rec["hostname"]
        aliases = rec.get("aliases")
        if aliases:
            names = names + " " + " ".join(aliases)
        for key in ("ipv4", "ipv6"):
            ip = rec.get(key)
            if ip:
                lines.append(ip + "\t" + names)
    lines.sort()
    return _HEADER + "\n" + "".join(line + "\n" for line in lines)


def write_hosts_file(path, records):
    """Atomically write rendered hosts to `path`; return True iff it changed.

    If `path` already holds the rendered content, do nothing and return False
    (no dnsmasq reload churn). Otherwise write to a sibling temp file and
    os.replace() it into place (atomic on the same filesystem).
    """
    rendered = render_hosts(records)
    try:
        with open(path, "r") as fh:
            if fh.read() == rendered:
                return False
    except FileNotFoundError:
        pass
    tmp = path + ".tmp"
    with open(tmp, "w") as fh:
        fh.write(rendered)
    os.replace(tmp, path)
    return True
