---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
  children:
    arista:
      hosts:
        rabbit-rhythm:
          ansible_ssh_extra_args: "-o ProxyCommand='ssh -W %h:%p bang-rhythm'"
        rabbit-blues:
          ansible_ssh_extra_args: "-o ProxyCommand='ssh -W %h:%p bang-blues'"
    cumulus:
      hosts:
        turtle-rhythm:
    jumphosts:
      hosts:
        bang-rhythm:
          ansible_host: "{{ bang_rhythm_ts_ip }}"
        bang-blues:
          ansible_host: "{{ bang_blues_ts_ip }}"
