---
- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart flax-reconcile
  become: true
  ansible.builtin.systemd:
    name: flax-reconcile.service
    state: restarted

- name: Reload firewalld
  become: true
  ansible.builtin.command:
    cmd: firewall-cmd --reload
  changed_when: true
